# name: Cppcheck
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install Cppcheck
#       run: sudo apt-get install cppcheck

#     - name: Run Cppcheck
#       run: cppcheck --enable=all --inconclusive --xml --xml-version=2 . 2> cppcheck-result.xml

#     - name: Upload Cppcheck results
#       uses: actions/upload-artifact@v2
#       with:
#         name: cppcheck-result
#         path: cppcheck-result.xml

#     - name: Annotate Cppcheck results
#       run: |
#         echo "::group::Cppcheck Annotations"
#         grep "<error " cppcheck-result.xml | while read -r line; do
#           file=$(echo "$line" | grep -oP 'file="\K[^"]+')
#           line=$(echo "$line" | grep -oP 'line="\K[^"]+')
#           message=$(echo "$line" | grep -oP 'msg="\K[^"]+')
#           echo "::warning file=$file,line=$line::Cppcheck: $message"
#         done
#         echo "::endgroup::"
